
name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: https://api.paranhospr.com.br
        
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Build completed successfully"
        echo "Render will automatically deploy from this repository"
        echo "Make sure to configure Render service to:"
        echo "- Build Command: npm ci && npm run build"
        echo "- Start Command: npm start"
        echo "- Environment: NEXT_PUBLIC_API_URL=https://api.paranhospr.com.br"
